name: Build Flet APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем твой код
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Устанавливаем Flutter (как ты и сделал)
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Создаем чистое Flutter-приложение
      - name: Create Flutter App
        run: flutter create android_app

      # 4. Копируем твой код внутрь приложения
      - name: Copy Python files
        run: |
          cp dashboard_flet.py android_app/
          cp telegram_api.py android_app/
          echo "requests" > android_app/requirements.txt
          echo "supabase" >> android_app/requirements.txt

      # 5. Настраиваем зависимости Flutter (как мы делали локально)
      - name: Configure pubspec.yaml
        run: |
          cd android_app
          flutter pub add flet
          flutter pub add python_channel

      # 6. Создаем правильный main.dart (как мы делали локально)
      - name: Create main.dart
        run: |
          echo '''
          import 'package:flet/flet.dart';
          import 'package:flutter/material.dart';
          import 'package:python_channel/python_channel.dart';

          void main() async {
            await Flet.setupDesktop();
            runApp(const MyApp());
          }

          class MyApp extends StatelessWidget {
            const MyApp({super.key});

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                home: FletPythonApp(
                  pythonChannel: PythonChannel(
                    script: 'dashboard_flet.py',
                  ),
                ),
              );
            }
          }
          ''' > android_app/lib/main.dart

      # 7. Устанавливаем Python-зависимости
      - name: Install Python deps
        run: pip install -r android_app/requirements.txt

      # 8. ЗАПУСКАЕМ НАСТОЯЩУЮ СБОРКУ
      - name: Build APK
        run: |
          cd android_app
          flutter build apk

      # 9. Отдаем тебе готовый APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: android_app/build/app/outputs/flutter-apk/app-release.apk
