name: Build Flet APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: stable

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Build APK
        run: flet build apk --module-name dashboard_flet

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: |
            build/apk/*.apk
            build/**/apk/*.apk
